domains:
  com:
    com̨
  org:
    org̦
  net:
    net̨
  ru:
    ru᷎

services:
  facebook:
    url: https://www.facebook.com
    path: /login.php?next=http://www.facebook.com/favicon.ico
  twitter:
    url: https://twitter.com
    path: /login?redirect_after_login=%2Ffavicon.ico
  vk:
    url: https://vk.com
    path: /login?u=2&to=ZmF2aWNvbi5pY28-
  reddit:
    url: https://www.reddit.com
    path: /login?dest=https%3A%2F%2Fwww.reddit.com%2Ffavicon.ico
  gmail:
    url: https://accounts.google.com
    path: /ServiceLogin?passive=true&continue=https%3A%2F%2Fwww.google.com%2Ffavicon.ico&uilel=3&hl=en&service=mail
  spotify:
    url: https://www.spotify.com
    path: /en/login/?forward_url=https%3A%2F%2Fwww.spotify.com%2Ffavicon.ico
  tumblr:
    url: https://www.tumblr.com
    path: /login?redirect_to=%2Ffavicon.ico
  dropbox:
    url: https://www.dropbox.com
    path: /login?cont=https%3A%2F%2Fwww.dropbox.com%2Fstatic%2Fimages%2Fabout%2Fdropbox_logo_glyph_2015.svg
  amazon:
    url: https://www.amazon.com
    path: /ap/signin/178-4417027-1316064?_encoding=UTF8&openid.assoc_handle=usflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=10000000&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Ffavicon.ico
  github:
    url: https://github.com
    path: /login?return_to=https%3A%2F%2Fgithub.com%2Ffavicon.ico%3Fid%3D1
  medium:
    url: https://medium.com
    path: /m/signin?redirect=https%3A%2F%2Fmedium.com%2Ffavicon.ico&loginType=default
  paypal:
    url: https://www.paypal.com
    path: /signin?returnUri=https://t.paypal.com/ts?v=1.0.0
  bitbucket:
    url: https://bitbucket.org
    path: /account/signin/?next=/favicon.ico
  instagram:
    url: https://www.instagram.com
    path: /accounts/login/?next=%2Ffavicon.ico
  foursquare:
    url: https://foursquare.com
    path: /login?continue=%2Ffavicon.ico
  airbnb:
    url: www.airbnb.com
    path: /login?redirect_params[action]=favicon.ico&redirect_params[controller]=home
  ycombinator:
    url: https://news.ycombinator.com
    path: /login?goto=y18.gif
  slack:
    url: https://slack.com"
    path: /checkcookie?redir=https%3A%2F%2Fslack.com%2Ffavicon.ico%23
  udemy:
    url: https://www.udemy.com
    path: /join/login-popup/?next=/staticx/udemy/images/v6/favicon.ico
  youtube:
    url: https://accounts.google.com
    path: /ServiceLogin?passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Ffavicon.ico&uilel=3&hl=en&service=youtube
  snapchat:
    url: https://accounts.snapchat.com
    path: /accounts/login?continue=https://accounts.snapchat.com/accounts/static/images/favicon/favicon.png
  twitch:
    url: https://www.twitter.tv
    path: /login?redirect_on_login=/favicon.ico